# Generated by Django 5.2.5 on 2025-08-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('News', 'News'), ('Sports', 'Sports'), ('Politics', 'Politics'), ('Technology', 'Technology'), ('Lifestyle', 'Lifestyle'), ('Business', 'Business'), ('Weather', 'Weather')], default='News', max_length=100),
        ),
    ]
